### ISSUE TITLE
[AETR] Add rendered PDF to book

### ISSUE THREAD

**Issue by eldobbins** [acep-uaf/aetr-web-book-2024#57]
Neil found it easier to work with PDFs rather than the web pages.

- what would it do to interactive figures?
- how to link?

Example: https://openscapes.github.io/booklet/. (see the PDF symbol under the icon in the left margin?)

**Comment by eldobbins** [comment]
Have experimented with rendering as PDF. Quarto uses KOMA-script to use defined LaTeX document classes, so formatting a report is super easy.
- [PDF Basics](https://quarto.org/docs/output-formats/pdf-basics.html)
- [PDF Options](https://quarto.org/docs/reference/formats/pdf.html)

Working and looking good:
- and R code in the pages renders fine (i.e. the values calculated in the text)
- sections cross-references also working
- Table of contents even for figures and tables. And this is clickable so can be used to navigate to the correct pages.
- page numbers
- external links

Problems:
- footnotes not working
- table of reports is not formatted nicely. columns running into each other

So considering just those things, generating a PDF is pretty easy...

# BUT!
[ojs figures are rendered by the browser](https://github.com/quarto-dev/quarto-cli/discussions/1909#discussioncomment-3403582) when the HTML pages are viewed - not by Quarto. So the rendered PDF only has code - not the figures.

Quarto "recommends" to print pages from the browser to PDF files = twisted. In 2022, the prediction was that adding ojs rendering would be implemented in 3-9 months.  

Also:
- [Quarto - OJS fails to render but previews](https://forum.posit.co/t/quarto-ojs-fails-to-render-but-previews/155539)
- [OJS - not locally interactive #2529](https://github.com/quarto-dev/quarto-cli/issues/2529)

**Comment by eldobbins** [comment]
How to print website to PDF?

- https://www.adobe.com/acrobat/how-to/convert-html-to-pdf.html
- https://www.tutorialspoint.com/how-do-i-export-my-html-page-as-a-pdf-using-javascript
- https://wkhtmltopdf.org
- https://phantomjs.org (development suspended)

Note: the Quarto rendered HTML pages (`_site/methods.html`) are full of javascript not static images in `_site_images`. Of course! That was the point.  So the converter has to render the js.

**Comment by ianalexmac** [comment]
At the moment, we are in a bind over two issues:
<br>
First of all, our figures are built in OJS, which needs some workarounds to render into a static images. 
- This can be accomplished by some clever code using [puppeteer](https://pptr.dev), where a headless browser is spun up and screenshots of the figures are saved to file. 
- Each figure needs a unique CSS selector tag prior to screenshotting, but otherwise the code is straightforward and can be iterated over multiple figures. 

<br>
<br>

Second, Quarto has conditional code execution, but only for R blocks. So we can't turn OJS blocks on/off depending on render format. 
- Even worse, the OJS code can't be hidden, so when rendered to PDF the code is just out there with the text. Not ideal.
- However, if we abstract the OJS code to separate scripts, then we can call those scripts using conditional R code blocks. This might require a single script for each figure, so the directories would need to be well organized. 
- Pulling OJS code out of the QMD files and calling via R might be the workaround we need to maintain a single code base that can render both a PDF and a web page.

**Comment by eldobbins** [comment]
What if we thought of the PDF as a different beast with static figures, not as a differently rendered version of the interactive figures? That would broaden the applicability of Quarto to article and report generation without relying on an intermediate interactive version.

The steps of this would look like
1. Liz pushes the change to https://github.com/eldobbins/new-quarto-website that renders R
2. Ian forks that repo, and adds a code block to index.qmd with the condition code execution
  * option 1 renders a "Hello World" type plot in R
  * option 2 renders an OJS version of the same plot as an interactive version
 3. Ian makes a PR back to new-quarto-website so Liz can clearly see the changes he had to make
 4. Liz migrates those changes to the cookiecutter so that it can now generate a repo that can produce both interactive plots or static plots depending on the render
 5. Meanwhile, Ian uses his stripped down example to teach Emily about Quarto and plots
 6. Ian and Emily have a hackathon to add a static option to every plot in AETR that will be used in the PDF.

Deadline for this would be July 1
