### ISSUE TITLE
Set theme for PDF figures

### ISSUE THREAD

**Issue by ianalexmac** [acep-uaf/aetr-web-book-2024#80]
We would really like some universal theming of the ggplot graphs (such as size of graph, fonts etc). Please investigate best ways to do so.

**Comment by emr65df** [comment]
just to comment on this, the length of some legends in the installed capacity graphs are so long that to keep the figure as close to the original as possible the fonts are small, as well as the legend keys. This can be fixed by altering the legend (make two lines instead of one line) in order to prevent it from being cut off and to also conform to a larger font size.

**Comment by emr65df** [comment]
The newly rendered PDF does cut off the long legend in installed capacity. @ianalexmac
